language: java
jdk: openjdk9

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
addons:
  sonarcloud:
    organization: "climatetree"
    token:
      secure: "Q3D1LS9QnIFLTu+AUWPb+ji2T/XtD6wSsn4B+gEgt96qABsbrJBw9WxvNcz9/ON/1VEBKWGfejr0DE4QEe4+Z536FBuvpCcLHiXvdVSPgzWlDa2eqGU5IbW6BlAlA3Gic3woEpyhGVFkyRGEy3bkGfQXk9T/Xv2MwRwSiWYJu+nnEi6vWj4b+Ke84JJ4BRFePu4eUYzKyV7wWapqBAYycc6+S3ws+6vkl8t5zfF32mkYImFvi+5Fr24Q0MMkGCI/+P3Jr74Fqzba1cACBC7tQylcIRqruSRyKQlYia14Jp2QFpwsM0Fk1nKBkmFbB+Y6Ic95kyJJZT/Ew6Xi42ZPnxaWBGKUFJAw3CNHpvLpxoFQRB1f5c4+F/0Q02W4xXnhTtki7U2sk6zFNEdYXgjVo5s/sVMKb86BvCNI9VqEwy7jHQZuvl+ajOqe1G1IzBbbJKQng+j8Bkh77/e2Qg1SbinE46qf9x98W9LuxhHJAXYEeEw4+PLYLOR95pBtKl3kD9dEWjuGnW3ePwohS8t60FogFxL+3spaNhwQrtS/yHjj9+N6nBtJK0fZlHdIuJ18Cm6ZSyp4jj1cSeU8R4/uPnFF/HuApQJvAPc2QPBdWfIB3etfNSad1AhDV3p9vUh+4zF5hw7jM6o/TVUDLyu4myHOaF683VaAg5cuk28IH1k=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar