language: java
jdk: openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

services:
  - postgresql

before_script:
  - psql -c 'create database POSTGRESQL;' -U postgres

addons:
  sonarcloud:
    organization: climatetree
    token:
      secure: "VFAJMwPe4Earo+R1DYlxDYhYYS2Qrgc5tkccq58zAlOv2R6OzFiCiRlolKX57F5JX3+Eo1nH2DI05NTyd8fIw6QxdkFtzlpEQ+aLpeLSXvY7ouTo8hO8/9SBPgu2Q6+GxXudcL+bpxB6X8lRoiQfjiKoxbg6joJZLxp8h0ugvsVGYxmwxxXiaWxH1fE2FdSNuH/X2MhVUZzyFSxstf6k0E0SXTlhWTxB2yogP7woiZ53lmU7XZJNir5H19Gnb7pTPNwNEMD0IgdDZSpIuRbuekO6NdFxiMi1B+P/2wzfEU+pTX0H+NJffaFZFcoRYlSMMH4Gwd6ijqyZ5v9rKzdVkYW3M0/uOB31U4stRYEEctf9C+cfGihdAO9Q/jfTkPO51cEAQkF4TtVryCzuqg7moudugbDHCXGxxe9H9DtHCawjCTBPIAG+XJF8vwsTmNmVXuk6cQe0IlXjmokn3j5eIK6A5jvvJJ28Y62hfmHhiHl7l1uMlNCPjoZ56X92rPbaJhwJ+70WJdZslBFp69M4my/yLDaPlZdQIb2biD7LFa+ZZ+wp43DoHI0eRK8Tucf223SR9+Nsjcgz3w31dpRRgwuSxvDUNo2LVIYumq4y+MTrS07Ks2pk7hD+kANE5znZRNlXrKA/0slcOLu6QiqMCjaFEOkVwmdiLMF4bP/0Wic="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean test
  - sonar-scanner

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master